/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "ftsTimingTable.h"

/** Initializes the ftsTimingTable module */
void
init_ftsTimingTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_ftsTimingTable();
}


/** Initialize the ftsTimingTable table by defining its contents and how it's structured */
void
initialize_table_ftsTimingTable(void)
{
    const oid ftsTimingTable_oid[] = {1,3,6,1,4,1,63000,2,1,13,1,2,1,12,3};
    const size_t ftsTimingTable_oid_len   = OID_LENGTH(ftsTimingTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_tdata                   *table_data;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("ftsTimingTable:init", "initializing table ftsTimingTable\n"));

    reg = netsnmp_create_handler_registration(
              "ftsTimingTable",     ftsTimingTable_handler,
              ftsTimingTable_oid, ftsTimingTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_data = netsnmp_tdata_create_table( "ftsTimingTable", 0 );
    if (NULL == table_data) {
        snmp_log(LOG_ERR,"error creating tdata table for ftsTimingTable\n");
        return;
    }
    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    if (NULL == table_info) {
        snmp_log(LOG_ERR,"error creating table info for ftsTimingTable\n");
        return;
    }
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: ftsTimingIndex */
                           0);

    table_info->min_column = COLUMN_FTSTIMINGINDEX;
    table_info->max_column = COLUMN_FTSTIMINGDESCR;
    
    netsnmp_tdata_register( reg, table_data, table_info );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct ftsTimingTable_entry {
    /* Index values */
    long ftsTimingIndex;

    /* Column values */
    long ftsTimingIndex;
    long ftsTimingState;
    long old_ftsTimingState;
    long ftsTimingDescr;

    int   valid;
};

/* create a new row in the table */
netsnmp_tdata_row *
ftsTimingTable_createEntry(netsnmp_tdata *table_data
                 , long  ftsTimingIndex
                ) {
    struct ftsTimingTable_entry *entry;
    netsnmp_tdata_row *row;

    entry = SNMP_MALLOC_TYPEDEF(struct ftsTimingTable_entry);
    if (!entry)
        return NULL;

    row = netsnmp_tdata_create_row();
    if (!row) {
        SNMP_FREE(entry);
        return NULL;
    }
    row->data = entry;

    DEBUGMSGT(("ftsTimingTable:entry:create", "row 0x%x\n", (uintptr_t)row));
    entry->ftsTimingIndex = ftsTimingIndex;
    netsnmp_tdata_row_add_index( row, ASN_INTEGER,
                                 &(entry->ftsTimingIndex),
                                 sizeof(entry->ftsTimingIndex));
    if (table_data)
        netsnmp_tdata_add_row( table_data, row );
    return row;
}

/* remove a row from the table */
void
ftsTimingTable_removeEntry(netsnmp_tdata     *table_data, 
                 netsnmp_tdata_row *row) {
    struct ftsTimingTable_entry *entry;

    if (!row)
        return;    /* Nothing to remove */

    DEBUGMSGT(("ftsTimingTable:entry:remove", "row 0x%x\n", (uintptr_t)row));

    entry = (struct ftsTimingTable_entry *)row->data;
    SNMP_FREE( entry );   /* XXX - release any other internal resources */

    if (table_data)
        netsnmp_tdata_remove_and_delete_row( table_data, row );
    else
        netsnmp_tdata_delete_row( row );    
}


/** handles requests for the ftsTimingTable table */
int
ftsTimingTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    netsnmp_tdata              *table_data;
    netsnmp_tdata_row          *table_row;
    struct ftsTimingTable_entry          *table_entry;
    int                         ret;

    DEBUGMSGTL(("ftsTimingTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            if (request->processed)
                continue;

            table_entry = (struct ftsTimingTable_entry *)
                              netsnmp_tdata_extract_entry(request);
            table_info  =     netsnmp_extract_table_info( request);
    
            switch (table_info->colnum) {
            case COLUMN_FTSTIMINGINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ftsTimingIndex);
                break;
            case COLUMN_FTSTIMINGSTATE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ftsTimingState);
                break;
            case COLUMN_FTSTIMINGDESCR:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ftsTimingDescr);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            if (request->processed)
                continue;

            table_entry = (struct ftsTimingTable_entry *)
                              netsnmp_tdata_extract_entry(request);
            table_info  =     netsnmp_extract_table_info( request);
    
            switch (table_info->colnum) {
            case COLUMN_FTSTIMINGSTATE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            if (request->processed)
                continue;

            table_entry = (struct ftsTimingTable_entry *)
                              netsnmp_tdata_extract_entry(request);
            table_info  =     netsnmp_extract_table_info( request);
    
            switch (table_info->colnum) {
            case COLUMN_FTSTIMINGSTATE:
                table_entry->old_ftsTimingState = table_entry->ftsTimingState;
                table_entry->ftsTimingState     = *request->requestvb->val.integer;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            if (request->processed)
                continue;

            table_entry = (struct ftsTimingTable_entry *)
                              netsnmp_tdata_extract_entry(request);
            table_row   =     netsnmp_tdata_extract_row(  request);
            table_data  =     netsnmp_tdata_extract_table(request);
            table_info  =     netsnmp_extract_table_info( request);
    
            switch (table_info->colnum) {
            case COLUMN_FTSTIMINGSTATE:
                table_entry->ftsTimingState     = table_entry->old_ftsTimingState;
                table_entry->old_ftsTimingState = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
