/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef FTS_SCALAR_H
#define FTS_SCALAR_H

/* function declarations */
void init_fts_scalar(void);
Netsnmp_Node_Handler handle_ftsRefCfg;
Netsnmp_Node_Handler handle_ftsRefCurrent;
Netsnmp_Node_Handler handle_ftsClkState;
Netsnmp_Node_Handler handle_ftsClkMode;
Netsnmp_Node_Handler handle_ftsClkTimeAccuracy;
Netsnmp_Node_Handler handle_ftsClkFreqAccuracy;
Netsnmp_Node_Handler handle_ftsClkTimeThreshold;
Netsnmp_Node_Handler handle_ftsClkGrade;
Netsnmp_Node_Handler handle_ftsClkCurrentStateLast;
Netsnmp_Node_Handler handle_ftsClkClass;
Netsnmp_Node_Handler handle_ftsNtpNums;
Netsnmp_Node_Handler handle_ftsPtpNums;
Netsnmp_Node_Handler handle_ftsTimingCfg;

#endif /* FTS_SCALAR_H */
