/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

//#include <stdio.h>
#include <string.h>

#include "ftsRefCfg.h"

#define FTS_STRING_LEN 64

char var_ftsRefCfg[FTS_STRING_LEN];
int var_ftsRefCurrent;




/** Initializes the ftsRefCfg module */
void
init_fts_scalar(void)
{
    const oid ftsRefCfg_oid[] = { 1,3,6,1,4,1,63000,2,1,13,1,2,1,1,1 };
    const oid ftsRefCurrent_oid[] = { 1,3,6,1,4,1,63000,2,1,13,1,2,1,1,2 };
	const oid ftsClkState_oid[] = { 1,3,6,1,4,1,63000,2,1,13,1,2,1,2,1 };
	const oid ftsClkMode_oid[] = { 1,3,6,1,4,1,63000,2,1,13,1,2,1,2,2 };
	const oid ftsClkTimeAccuracy_oid[] = { 1,3,6,1,4,1,63000,2,1,13,1,2,1,2,4 };
	const oid ftsClkFreqAccuracy_oid[] = { 1,3,6,1,4,1,63000,2,1,13,1,2,1,2,5 };
	const oid ftsClkTimeThread_oid[] = { 1,3,6,1,4,1,63000,2,1,13,1,2,1,2,6 };
	const oid ftsClkFreqThread_oid[] = { 1,3,6,1,4,1,63000,2,1,13,1,2,1,2,7 };
	const oid ftsClkGrade_oid[] = { 1,3,6,1,4,1,63000,2,1,13,1,2,1,2,8 };
	const oid ftsClkCurrentStateLast_oid[] = { 1,3,6,1,4,1,63000,2,1,13,1,2,1,2,9 };
	const oid ftsClkClass_oid[] = { 1,3,6,1,4,1,63000,2,1,13,1,2,1,2,10 };

  DEBUGMSGTL(("ftsRefCfg", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("ftsRefCfg", handle_ftsRefCfg,
                               ftsRefCfg_oid, OID_LENGTH(ftsRefCfg_oid),
                               HANDLER_CAN_RWRITE
        ));
	//init fts
	strcpy(var_ftsRefCfg, "GPS");
}

int
handle_ftsRefCfg(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {


        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     var_ftsRefCfg/* XXX: a pointer to the scalar's data */,
                                     FTS_STRING_LEN/* XXX: the length of the data in bytes */);
            break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
        case MODE_SET_RESERVE1:
                /* or you could use netsnmp_check_vb_type_and_size instead */
            ret = netsnmp_check_vb_type(requests->requestvb, ASN_OCTET_STR);
            if ( ret != SNMP_ERR_NOERROR ) {
                netsnmp_set_request_error(reqinfo, requests, ret );
            }
            break;

        case MODE_SET_RESERVE2:
            /* XXX malloc "undo" storage buffer */
           // if (/* XXX if malloc, or whatever, failed: */) {
            //    netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_RESOURCEUNAVAILABLE);
          //  }
            break;

        case MODE_SET_FREE:
            /* XXX: free resources allocated in RESERVE1 and/or
               RESERVE2.  Something failed somewhere, and the states
               below won't be called. */
            break;

        case MODE_SET_ACTION:
	    //value =  *(requests->requestvb->val.integer);
		strcpy(var_ftsRefCfg, requests->requestvb->val.string);
            //rc = netsnmp_arch_ip_scalars_ipDefaultTTL_set(value);
            //if ( 0 != rc ) {
              //  netsnmp_set_request_error(reqinfo, requests, rc);
           // }


            ///* XXX: perform the value change here */
           // if (/* XXX: error? */) {
            //    netsnmp_set_request_error(reqinfo, requests, /* some error */);
           // }
            break;

        case MODE_SET_COMMIT:
         //   /* XXX: delete temporary storage */
          //  if (/* XXX: error? */) {
           //     /* try _really_really_ hard to never get to this point */
           //     netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_COMMITFAILED);
           // }
            break;

        case MODE_SET_UNDO:
         //   /* XXX: UNDO and return to previous value for the object */
         //   if (/* XXX: error? */) {
         //       /* try _really_really_ hard to never get to this point */
          //      netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_UNDOFAILED);
           // }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_ftsRefCfg\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
