/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef FTSCLKTRAP_H
#define FTSCLKTRAP_H

/* function declarations */
int send_ftsClkTrap_trap(void);

void init_ftsClkTrap(void);


#endif /* FTSCLKTRAP_H */
