/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef FTSNTPTABLE_H
#define FTSNTPTABLE_H

/* function declarations */
void init_ftsNtpTable(void);
void initialize_table_ftsNtpTable(void);
Netsnmp_Node_Handler ftsNtpTable_handler;

/* column number definitions for table ftsNtpTable */
       #define COLUMN_FTSNTPINDEX		2
       #define COLUMN_FTSNTPSTATE		3
       #define COLUMN_FTSNTPCALLS		4
       #define COLUMN_FTSNTPREPLAYS		5
#endif /* FTSNTPTABLE_H */
