/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef FTSPTPTABLE_H
#define FTSPTPTABLE_H

/* function declarations */
void init_ftsPtpTable(void);
void initialize_table_ftsPtpTable(void);
Netsnmp_Node_Handler ftsPtpTable_handler;

/* column number definitions for table ftsPtpTable */
       #define COLUMN_FTSPTPINDEX		1
       #define COLUMN_FTSPTPSTATE		2
       #define COLUMN_FTSPTPDOMAIN		3
       #define COLUMN_FTSPTPDELAYREQS		4
       #define COLUMN_FTSPTPDELAYRESPS		5
#endif /* FTSPTPTABLE_H */
