/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef FTSREFTABLE_H
#define FTSREFTABLE_H

/* function declarations */
void init_ftsRefTable(void);
void initialize_table_ftsRefTable(void);
Netsnmp_Node_Handler ftsRefTable_handler;

/* column number definitions for table ftsRefTable */
       #define COLUMN_FTSREFINDEX		1
       #define COLUMN_FTSREFSTATE		2
       #define COLUMN_FTSREFDESCR		3
       #define COLUMN_FTSREFGRADE		4
#endif /* FTSREFTABLE_H */
