/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef FTSTIMINGTABLE_H
#define FTSTIMINGTABLE_H

/* function declarations */
void init_ftsTimingTable(void);
void initialize_table_ftsTimingTable(void);
Netsnmp_Node_Handler ftsTimingTable_handler;

/* column number definitions for table ftsTimingTable */
       #define COLUMN_FTSTIMINGINDEX		2
       #define COLUMN_FTSTIMINGSTATE		3
       #define COLUMN_FTSTIMINGDESCR		4
#endif /* FTSTIMINGTABLE_H */
